version: "3.9"

services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: >
      http --url=adequate-ray-main.ngrok-free.app host.docker.internal:5555
    ports:
      - "4040:4040" # Expose ngrok web inspector to host
